version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    environment:
      # For write permission of /games directory
      - PUID=1000
      - PGID=1000
      # Uncomment to setup basic auth
      # - USERNAME=a1ex
      # - PASSWORD=
    volumes:
      - /storage/media/games/switch:/games
    ports:
      - "8000:80"