version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    volumes:
      - /your/game/directory:/games
      # Uncomment if you want to edit and persist the app configuration
      # - ./app:/app
      # Uncomment to setup basic auth
      # - ./nginx:/etc/nginx
    ports:
      - "8000:80"